export const questions: string[] = [
  "Are you going to school tomorrow?",
  "Do you enjoy learning new things?",
  "Are you confident in your problem-solving skills?",
  "Do you work well in a team?",
  "Are you comfortable with public speaking?",
  "Do you have experience with project management?",
  "Are you proficient in using computer software?",
  "Do you regularly set personal goals?",
  "Are you satisfied with your current job?",
  "Do you seek feedback to improve your work?",
  "Do you manage your time effectively?",
  "Are you open to learning new technologies?",
  "Do you have strong written communication skills?",
  "Do you handle stress well?",
  "Are you good at networking?",
  "Do you regularly update your skills?",
  "Are you a good listener?",
  "Do you enjoy working independently?",
  "Do you have experience in coding?",
  "Do you enjoy solving complex problems?",
  "Are you interested in pursuing further education?",
];
